-- ============================================================
-- EngLear — grammar topics A1–C2 (titles in the 11 interface languages).
-- Idempotent; run after 0018. Adds rows only: an existing code is left as it is.
-- ============================================================

insert into public.grammar_topics (code, cefr, titles, position) values
  ('to-be', 'A1', '{"en":"Verb “to be”","ru":"Глагол to be","uk":"Дієслово to be","de":"Das Verb „to be“","fr":"Le verbe « to be »","es":"El verbo “to be”","it":"Il verbo “to be”","pt":"O verbo “to be”","pl":"Czasownik „to be”","zh":"动词 to be","ja":"動詞 to be"}'::jsonb, 10),
  ('personal-pronouns', 'A1', '{"en":"Personal pronouns","ru":"Личные местоимения","uk":"Особові займенники","de":"Personalpronomen","fr":"Pronoms personnels","es":"Pronombres personales","it":"Pronomi personali","pt":"Pronomes pessoais","pl":"Zaimki osobowe","zh":"人称代词","ja":"人称代名詞"}'::jsonb, 20),
  ('possessive-adjectives', 'A1', '{"en":"Possessive adjectives (my, your, his…)","ru":"Притяжательные местоимения (my, your, his…)","uk":"Присвійні займенники (my, your, his…)","de":"Possessivbegleiter (my, your, his…)","fr":"Adjectifs possessifs (my, your, his…)","es":"Adjetivos posesivos (my, your, his…)","it":"Aggettivi possessivi (my, your, his…)","pt":"Adjetivos possessivos (my, your, his…)","pl":"Przymiotniki dzierżawcze (my, your, his…)","zh":"物主形容词（my, your, his…）","ja":"所有格（my, your, his…）"}'::jsonb, 30),
  ('articles-a-an', 'A1', '{"en":"Articles a / an","ru":"Артикли a / an","uk":"Артиклі a / an","de":"Artikel a / an","fr":"Articles a / an","es":"Artículos a / an","it":"Articoli a / an","pt":"Artigos a / an","pl":"Przedimki a / an","zh":"冠词 a / an","ja":"冠詞 a / an"}'::jsonb, 40),
  ('plural-nouns', 'A1', '{"en":"Plural nouns","ru":"Множественное число существительных","uk":"Множина іменників","de":"Plural der Nomen","fr":"Le pluriel des noms","es":"El plural de los sustantivos","it":"Il plurale dei nomi","pt":"Plural dos substantivos","pl":"Liczba mnoga rzeczowników","zh":"名词复数","ja":"名詞の複数形"}'::jsonb, 50),
  ('this-that', 'A1', '{"en":"This, that, these, those","ru":"This, that, these, those","uk":"This, that, these, those","de":"This, that, these, those","fr":"This, that, these, those","es":"This, that, these, those","it":"This, that, these, those","pt":"This, that, these, those","pl":"This, that, these, those","zh":"This, that, these, those","ja":"This, that, these, those"}'::jsonb, 60),
  ('there-is-are', 'A1', '{"en":"There is / there are","ru":"There is / there are","uk":"There is / there are","de":"There is / there are","fr":"There is / there are","es":"There is / there are","it":"There is / there are","pt":"There is / there are","pl":"There is / there are","zh":"There is / there are","ja":"There is / there are"}'::jsonb, 70),
  ('have-got', 'A1', '{"en":"Have got","ru":"Have got","uk":"Have got","de":"Have got","fr":"Have got","es":"Have got","it":"Have got","pt":"Have got","pl":"Have got","zh":"Have got","ja":"Have got"}'::jsonb, 80),
  ('present-simple', 'A1', '{"en":"Present Simple","ru":"Present Simple (настоящее простое)","uk":"Present Simple (теперішній простий час)","de":"Present Simple (einfache Gegenwart)","fr":"Present Simple (présent simple)","es":"Present Simple (presente simple)","it":"Present Simple (presente semplice)","pt":"Present Simple (presente simples)","pl":"Present Simple (czas teraźniejszy prosty)","zh":"一般现在时 (Present Simple)","ja":"現在形 (Present Simple)"}'::jsonb, 90),
  ('can-ability', 'A1', '{"en":"Can / can’t","ru":"Can / can’t (могу / не могу)","uk":"Can / can’t (можу / не можу)","de":"Can / can’t (können)","fr":"Can / can’t (pouvoir)","es":"Can / can’t (poder)","it":"Can / can’t (potere)","pt":"Can / can’t (poder)","pl":"Can / can’t (móc)","zh":"Can / can’t（能 / 不能）","ja":"Can / can’t（できる / できない）"}'::jsonb, 100),
  ('imperatives', 'A1', '{"en":"Imperatives","ru":"Повелительное наклонение","uk":"Наказовий спосіб","de":"Imperativ","fr":"L’impératif","es":"El imperativo","it":"L’imperativo","pt":"O imperativo","pl":"Tryb rozkazujący","zh":"祈使句","ja":"命令文"}'::jsonb, 110),
  ('prepositions-time-place', 'A1', '{"en":"Prepositions of time and place (in, on, at)","ru":"Предлоги времени и места (in, on, at)","uk":"Прийменники часу й місця (in, on, at)","de":"Präpositionen der Zeit und des Ortes (in, on, at)","fr":"Prépositions de temps et de lieu (in, on, at)","es":"Preposiciones de tiempo y lugar (in, on, at)","it":"Preposizioni di tempo e luogo (in, on, at)","pt":"Preposições de tempo e lugar (in, on, at)","pl":"Przyimki czasu i miejsca (in, on, at)","zh":"时间和地点介词（in, on, at）","ja":"時と場所の前置詞（in, on, at）"}'::jsonb, 120),
  ('question-words', 'A1', '{"en":"Question words (what, where, when…)","ru":"Вопросительные слова (what, where, when…)","uk":"Питальні слова (what, where, when…)","de":"Fragewörter (what, where, when…)","fr":"Mots interrogatifs (what, where, when…)","es":"Palabras interrogativas (what, where, when…)","it":"Parole interrogative (what, where, when…)","pt":"Palavras interrogativas (what, where, when…)","pl":"Słowa pytające (what, where, when…)","zh":"疑问词（what, where, when…）","ja":"疑問詞（what, where, when…）"}'::jsonb, 130),
  ('object-pronouns', 'A2', '{"en":"Object pronouns (me, him, us…)","ru":"Объектные местоимения (me, him, us…)","uk":"Об’єктні займенники (me, him, us…)","de":"Objektpronomen (me, him, us…)","fr":"Pronoms compléments (me, him, us…)","es":"Pronombres de objeto (me, him, us…)","it":"Pronomi complemento (me, him, us…)","pt":"Pronomes oblíquos (me, him, us…)","pl":"Zaimki w dopełnieniu (me, him, us…)","zh":"宾格代词（me, him, us…）","ja":"目的格の代名詞（me, him, us…）"}'::jsonb, 140),
  ('present-continuous', 'A2', '{"en":"Present Continuous","ru":"Present Continuous (настоящее длительное)","uk":"Present Continuous (теперішній тривалий час)","de":"Present Continuous (Verlaufsform der Gegenwart)","fr":"Present Continuous (présent progressif)","es":"Present Continuous (presente continuo)","it":"Present Continuous (presente progressivo)","pt":"Present Continuous (presente contínuo)","pl":"Present Continuous (czas teraźniejszy ciągły)","zh":"现在进行时 (Present Continuous)","ja":"現在進行形 (Present Continuous)"}'::jsonb, 150),
  ('past-simple-be', 'A2', '{"en":"Past Simple: was / were","ru":"Past Simple: was / were","uk":"Past Simple: was / were","de":"Past Simple: was / were","fr":"Past Simple : was / were","es":"Past Simple: was / were","it":"Past Simple: was / were","pt":"Past Simple: was / were","pl":"Past Simple: was / were","zh":"一般过去时：was / were","ja":"過去形：was / were"}'::jsonb, 160),
  ('past-simple', 'A2', '{"en":"Past Simple","ru":"Past Simple (прошедшее простое)","uk":"Past Simple (минулий простий час)","de":"Past Simple (einfache Vergangenheit)","fr":"Past Simple (prétérit)","es":"Past Simple (pasado simple)","it":"Past Simple (passato semplice)","pt":"Past Simple (passado simples)","pl":"Past Simple (czas przeszły prosty)","zh":"一般过去时 (Past Simple)","ja":"過去形 (Past Simple)"}'::jsonb, 170),
  ('countable-uncountable', 'A2', '{"en":"Countable and uncountable nouns (some, any)","ru":"Исчисляемые и неисчисляемые (some, any)","uk":"Злічувані й незлічувані (some, any)","de":"Zählbare und nicht zählbare Nomen (some, any)","fr":"Noms dénombrables et indénombrables (some, any)","es":"Sustantivos contables e incontables (some, any)","it":"Nomi numerabili e non numerabili (some, any)","pt":"Substantivos contáveis e incontáveis (some, any)","pl":"Rzeczowniki policzalne i niepoliczalne (some, any)","zh":"可数与不可数名词（some, any）","ja":"可算・不可算名詞（some, any）"}'::jsonb, 180),
  ('much-many', 'A2', '{"en":"Much, many, a lot of","ru":"Much, many, a lot of","uk":"Much, many, a lot of","de":"Much, many, a lot of","fr":"Much, many, a lot of","es":"Much, many, a lot of","it":"Much, many, a lot of","pt":"Much, many, a lot of","pl":"Much, many, a lot of","zh":"Much, many, a lot of","ja":"Much, many, a lot of"}'::jsonb, 190),
  ('comparatives', 'A2', '{"en":"Comparatives","ru":"Сравнительная степень","uk":"Вищий ступінь порівняння","de":"Komparativ","fr":"Le comparatif","es":"El comparativo","it":"Il comparativo","pt":"O comparativo","pl":"Stopień wyższy","zh":"比较级","ja":"比較級"}'::jsonb, 200),
  ('superlatives', 'A2', '{"en":"Superlatives","ru":"Превосходная степень","uk":"Найвищий ступінь порівняння","de":"Superlativ","fr":"Le superlatif","es":"El superlativo","it":"Il superlativo","pt":"O superlativo","pl":"Stopień najwyższy","zh":"最高级","ja":"最上級"}'::jsonb, 210),
  ('adverbs-frequency', 'A2', '{"en":"Adverbs of frequency (always, often, never…)","ru":"Наречия частотности (always, often, never…)","uk":"Прислівники частотності (always, often, never…)","de":"Häufigkeitsadverbien (always, often, never…)","fr":"Adverbes de fréquence (always, often, never…)","es":"Adverbios de frecuencia (always, often, never…)","it":"Avverbi di frequenza (always, often, never…)","pt":"Advérbios de frequência (always, often, never…)","pl":"Przysłówki częstotliwości (always, often, never…)","zh":"频率副词（always, often, never…）","ja":"頻度の副詞（always, often, never…）"}'::jsonb, 220),
  ('going-to', 'A2', '{"en":"Be going to","ru":"Be going to (планы)","uk":"Be going to (плани)","de":"Be going to (Pläne)","fr":"Be going to (projets)","es":"Be going to (planes)","it":"Be going to (progetti)","pt":"Be going to (planos)","pl":"Be going to (plany)","zh":"Be going to（打算）","ja":"Be going to（予定）"}'::jsonb, 230),
  ('will-future', 'A2', '{"en":"Future with will","ru":"Будущее время с will","uk":"Майбутній час з will","de":"Zukunft mit will","fr":"Le futur avec will","es":"El futuro con will","it":"Il futuro con will","pt":"O futuro com will","pl":"Czas przyszły z will","zh":"用 will 表示将来","ja":"will を使った未来"}'::jsonb, 240),
  ('must-have-to', 'A2', '{"en":"Must / have to","ru":"Must / have to (долженствование)","uk":"Must / have to (обов’язок)","de":"Must / have to (müssen)","fr":"Must / have to (obligation)","es":"Must / have to (obligación)","it":"Must / have to (obbligo)","pt":"Must / have to (obrigação)","pl":"Must / have to (obowiązek)","zh":"Must / have to（必须）","ja":"Must / have to（義務）"}'::jsonb, 250),
  ('present-perfect', 'B1', '{"en":"Present Perfect","ru":"Present Perfect (настоящее совершённое)","uk":"Present Perfect (теперішній доконаний час)","de":"Present Perfect","fr":"Present Perfect","es":"Present Perfect (pretérito perfecto)","it":"Present Perfect","pt":"Present Perfect","pl":"Present Perfect","zh":"现在完成时 (Present Perfect)","ja":"現在完了形 (Present Perfect)"}'::jsonb, 260),
  ('present-perfect-vs-past-simple', 'B1', '{"en":"Present Perfect or Past Simple","ru":"Present Perfect или Past Simple","uk":"Present Perfect чи Past Simple","de":"Present Perfect oder Past Simple","fr":"Present Perfect ou Past Simple","es":"Present Perfect o Past Simple","it":"Present Perfect o Past Simple","pt":"Present Perfect ou Past Simple","pl":"Present Perfect czy Past Simple","zh":"现在完成时还是一般过去时","ja":"現在完了形か過去形か"}'::jsonb, 270),
  ('past-continuous', 'B1', '{"en":"Past Continuous","ru":"Past Continuous (прошедшее длительное)","uk":"Past Continuous (минулий тривалий час)","de":"Past Continuous (Verlaufsform der Vergangenheit)","fr":"Past Continuous (passé progressif)","es":"Past Continuous (pasado continuo)","it":"Past Continuous (passato progressivo)","pt":"Past Continuous (passado contínuo)","pl":"Past Continuous (czas przeszły ciągły)","zh":"过去进行时 (Past Continuous)","ja":"過去進行形 (Past Continuous)"}'::jsonb, 280),
  ('used-to', 'B1', '{"en":"Used to","ru":"Used to (раньше, бывало)","uk":"Used to (раніше, бувало)","de":"Used to (früher)","fr":"Used to (habitudes passées)","es":"Used to (hábitos pasados)","it":"Used to (abitudini passate)","pt":"Used to (hábitos passados)","pl":"Used to (dawniej)","zh":"Used to（过去常常）","ja":"Used to（以前は～した）"}'::jsonb, 290),
  ('first-conditional', 'B1', '{"en":"First conditional","ru":"Условные предложения 1-го типа","uk":"Умовні речення 1-го типу","de":"Konditionalsatz Typ 1","fr":"Conditionnel de type 1","es":"Condicional de primer tipo","it":"Periodo ipotetico di primo tipo","pt":"Condicional do primeiro tipo","pl":"Pierwszy okres warunkowy","zh":"第一类条件句","ja":"第一条件文"}'::jsonb, 300),
  ('second-conditional', 'B1', '{"en":"Second conditional","ru":"Условные предложения 2-го типа","uk":"Умовні речення 2-го типу","de":"Konditionalsatz Typ 2","fr":"Conditionnel de type 2","es":"Condicional de segundo tipo","it":"Periodo ipotetico di secondo tipo","pt":"Condicional do segundo tipo","pl":"Drugi okres warunkowy","zh":"第二类条件句","ja":"第二条件文"}'::jsonb, 310),
  ('passive-basic', 'B1', '{"en":"Passive voice (present and past)","ru":"Пассивный залог (настоящее и прошедшее)","uk":"Пасивний стан (теперішній і минулий час)","de":"Passiv (Präsens und Präteritum)","fr":"La voix passive (présent et passé)","es":"La voz pasiva (presente y pasado)","it":"La forma passiva (presente e passato)","pt":"A voz passiva (presente e passado)","pl":"Strona bierna (czas teraźniejszy i przeszły)","zh":"被动语态（现在时和过去时）","ja":"受動態（現在と過去）"}'::jsonb, 320),
  ('relative-clauses', 'B1', '{"en":"Relative clauses (who, which, that)","ru":"Придаточные определительные (who, which, that)","uk":"Означальні підрядні речення (who, which, that)","de":"Relativsätze (who, which, that)","fr":"Propositions relatives (who, which, that)","es":"Oraciones de relativo (who, which, that)","it":"Frasi relative (who, which, that)","pt":"Orações relativas (who, which, that)","pl":"Zdania względne (who, which, that)","zh":"定语从句（who, which, that）","ja":"関係詞節（who, which, that）"}'::jsonb, 330),
  ('gerund-infinitive', 'B1', '{"en":"Gerund or infinitive","ru":"Герундий или инфинитив","uk":"Герундій чи інфінітив","de":"Gerundium oder Infinitiv","fr":"Gérondif ou infinitif","es":"Gerundio o infinitivo","it":"Gerundio o infinito","pt":"Gerúndio ou infinitivo","pl":"Gerundium czy bezokolicznik","zh":"动名词还是不定式","ja":"動名詞か不定詞か"}'::jsonb, 340),
  ('should-advice', 'B1', '{"en":"Should / ought to (advice)","ru":"Should / ought to (советы)","uk":"Should / ought to (поради)","de":"Should / ought to (Ratschläge)","fr":"Should / ought to (conseils)","es":"Should / ought to (consejos)","it":"Should / ought to (consigli)","pt":"Should / ought to (conselhos)","pl":"Should / ought to (rady)","zh":"Should / ought to（建议）","ja":"Should / ought to（助言）"}'::jsonb, 350),
  ('past-perfect', 'B2', '{"en":"Past Perfect","ru":"Past Perfect (предпрошедшее)","uk":"Past Perfect (давноминулий час)","de":"Past Perfect (Plusquamperfekt)","fr":"Past Perfect (plus-que-parfait)","es":"Past Perfect (pluscuamperfecto)","it":"Past Perfect (trapassato prossimo)","pt":"Past Perfect (mais-que-perfeito)","pl":"Past Perfect (czas zaprzeszły)","zh":"过去完成时 (Past Perfect)","ja":"過去完了形 (Past Perfect)"}'::jsonb, 360),
  ('third-conditional', 'B2', '{"en":"Third conditional","ru":"Условные предложения 3-го типа","uk":"Умовні речення 3-го типу","de":"Konditionalsatz Typ 3","fr":"Conditionnel de type 3","es":"Condicional de tercer tipo","it":"Periodo ipotetico di terzo tipo","pt":"Condicional do terceiro tipo","pl":"Trzeci okres warunkowy","zh":"第三类条件句","ja":"第三条件文"}'::jsonb, 370),
  ('reported-speech', 'B2', '{"en":"Reported speech","ru":"Косвенная речь","uk":"Непряма мова","de":"Indirekte Rede","fr":"Le discours indirect","es":"El estilo indirecto","it":"Il discorso indiretto","pt":"O discurso indireto","pl":"Mowa zależna","zh":"间接引语","ja":"間接話法"}'::jsonb, 380),
  ('modals-deduction', 'B2', '{"en":"Modals of deduction (must, might, can’t)","ru":"Модальные глаголы предположения (must, might, can’t)","uk":"Модальні дієслова припущення (must, might, can’t)","de":"Modalverben der Vermutung (must, might, can’t)","fr":"Modaux de déduction (must, might, can’t)","es":"Modales de deducción (must, might, can’t)","it":"Modali di deduzione (must, might, can’t)","pt":"Modais de dedução (must, might, can’t)","pl":"Czasowniki modalne przypuszczenia (must, might, can’t)","zh":"表推测的情态动词（must, might, can’t）","ja":"推量の助動詞（must, might, can’t）"}'::jsonb, 390),
  ('future-continuous-perfect', 'B2', '{"en":"Future Continuous and Future Perfect","ru":"Future Continuous и Future Perfect","uk":"Future Continuous і Future Perfect","de":"Future Continuous und Future Perfect","fr":"Future Continuous et Future Perfect","es":"Future Continuous y Future Perfect","it":"Future Continuous e Future Perfect","pt":"Future Continuous e Future Perfect","pl":"Future Continuous i Future Perfect","zh":"将来进行时和将来完成时","ja":"未来進行形と未来完了形"}'::jsonb, 400),
  ('passive-advanced', 'B2', '{"en":"Passive voice (all tenses)","ru":"Пассивный залог (все времена)","uk":"Пасивний стан (усі часи)","de":"Passiv (alle Zeiten)","fr":"La voix passive (tous les temps)","es":"La voz pasiva (todos los tiempos)","it":"La forma passiva (tutti i tempi)","pt":"A voz passiva (todos os tempos)","pl":"Strona bierna (wszystkie czasy)","zh":"被动语态（所有时态）","ja":"受動態（すべての時制）"}'::jsonb, 410),
  ('wish', 'B2', '{"en":"Wish / if only","ru":"Wish / if only (сожаление)","uk":"Wish / if only (жаль)","de":"Wish / if only (Wünsche)","fr":"Wish / if only (regrets)","es":"Wish / if only (deseos)","it":"Wish / if only (desideri)","pt":"Wish / if only (desejos)","pl":"Wish / if only (życzenia)","zh":"Wish / if only（愿望）","ja":"Wish / if only（願望）"}'::jsonb, 420),
  ('mixed-conditionals', 'C1', '{"en":"Mixed conditionals","ru":"Смешанные условные предложения","uk":"Змішані умовні речення","de":"Gemischte Konditionalsätze","fr":"Conditionnels mixtes","es":"Condicionales mixtos","it":"Periodi ipotetici misti","pt":"Condicionais mistos","pl":"Mieszane okresy warunkowe","zh":"混合条件句","ja":"混合条件文"}'::jsonb, 430),
  ('inversion', 'C1', '{"en":"Inversion (Never have I…)","ru":"Инверсия (Never have I…)","uk":"Інверсія (Never have I…)","de":"Inversion (Never have I…)","fr":"L’inversion (Never have I…)","es":"La inversión (Never have I…)","it":"L’inversione (Never have I…)","pt":"A inversão (Never have I…)","pl":"Inwersja (Never have I…)","zh":"倒装（Never have I…）","ja":"倒置（Never have I…）"}'::jsonb, 440),
  ('cleft-sentences', 'C1', '{"en":"Cleft sentences (It was… that, What I need is…)","ru":"Эмфатические конструкции (It was… that, What I need is…)","uk":"Емфатичні конструкції (It was… that, What I need is…)","de":"Spaltsätze (It was… that, What I need is…)","fr":"Phrases clivées (It was… that, What I need is…)","es":"Oraciones escindidas (It was… that, What I need is…)","it":"Frasi scisse (It was… that, What I need is…)","pt":"Orações clivadas (It was… that, What I need is…)","pl":"Zdania rozszczepione (It was… that, What I need is…)","zh":"分裂句（It was… that, What I need is…）","ja":"分裂文（It was… that, What I need is…）"}'::jsonb, 450),
  ('participle-clauses', 'C1', '{"en":"Participle clauses","ru":"Причастные обороты","uk":"Дієприкметникові звороти","de":"Partizipialsätze","fr":"Propositions participiales","es":"Oraciones de participio","it":"Proposizioni participiali","pt":"Orações reduzidas de particípio","pl":"Konstrukcje imiesłowowe","zh":"分词短语","ja":"分詞構文"}'::jsonb, 460),
  ('subjunctive', 'C2', '{"en":"The subjunctive (I suggest that he be…)","ru":"Сослагательное наклонение (I suggest that he be…)","uk":"Умовний спосіб (I suggest that he be…)","de":"Der Konjunktiv (I suggest that he be…)","fr":"Le subjonctif (I suggest that he be…)","es":"El subjuntivo (I suggest that he be…)","it":"Il congiuntivo (I suggest that he be…)","pt":"O subjuntivo (I suggest that he be…)","pl":"Tryb łączący (I suggest that he be…)","zh":"虚拟语气（I suggest that he be…）","ja":"仮定法現在（I suggest that he be…）"}'::jsonb, 470),
  ('hedging', 'C2', '{"en":"Hedging and softening (It would seem that…)","ru":"Смягчение утверждений (It would seem that…)","uk":"Пом’якшення тверджень (It would seem that…)","de":"Abschwächung von Aussagen (It would seem that…)","fr":"Atténuer ses propos (It would seem that…)","es":"Suavizar afirmaciones (It would seem that…)","it":"Attenuare le affermazioni (It would seem that…)","pt":"Suavizar afirmações (It would seem that…)","pl":"Łagodzenie wypowiedzi (It would seem that…)","zh":"委婉表达（It would seem that…）","ja":"断定を和らげる表現（It would seem that…）"}'::jsonb, 480)
on conflict (code) do nothing;

-- the starter library lesson on this topic
update public.lessons set grammar_topic_id = (select id from public.grammar_topics where code = 'present-simple')
 where scope = 'library' and source = 'import' and title = 'Present Simple: he, she, it' and grammar_topic_id is null;
